tests: de-duplicate spawnHttpServer to the common lib_test_uscan
Signed-off-by: Mattia Rizzolo <mattia@debian.org>

diff --git a/test/lib_test_uscan b/test/lib_test_uscan
--- a/test/lib_test_uscan
+++ b/test/lib_test_uscan
@@ -95,3 +95,24 @@ oneTimeTearDown () {
     rm -rf "$GPGHOME"
 }
 
+spawnHttpServer () {
+    unset http_proxy
+    local pid
+    [ -n "$TEMP_PKG_DIR" ] || fail "unexpected testsuite error"
+    (
+        mkdir -p "$TEMP_PKG_DIR"/repo
+        cd "$TEMP_PKG_DIR"/repo || exit 1
+        python3 "$test_dir/uscan/server.py" 2>log &
+        pid=$!
+        echo Starting: $pid
+        echo "$pid" > pid
+        while ! [ -s port ]; do
+            sleep 2s
+            if ! kill -0 "$pid" 2> /dev/null ; then
+                echo "The HTTP server returned an error:"
+                cat log
+                exit 1
+            fi
+        done
+    )
+}
