exit test if mktemp failed
this can fail if TMPDIR is exported, because on the second test it tries
to reuse the previous TMPDIR...

Signed-off-by: Mattia Rizzolo <mattia@debian.org>

diff --git a/test/test_uscan_git b/test/test_uscan_git
--- a/test/test_uscan_git
+++ b/test/test_uscan_git
@@ -65,6 +65,10 @@ PKG=foo
 makeDebianDir() {
     WATCHARGS=$1
     TMPDIR=$(mktemp -d)
+    if [ -z "$TMPDIR" ]; then
+        echo "Failed to create temporary directory" >&2
+        exit 1
+    fi
     mkdir -p $TMPDIR/$PKG/debian/upstream
     mkdir -p $TMPDIR/$PKG/debian/source
     spawnGitRepo
